
version: 2.1


jobs:
  build:
    docker:
      - image: cimg/base:stable
      
    working_directory: ~/repo
    
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - restore_cache:
          keys: 
            - v1-dependencies- {{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            
      - save_cache:
            path: 
              - ./venv
            key:
              - v1-dependencies- {{ checksum "requirements.txt" }}
      - run: 
          name: run lint
          command: |
            . venv/bin/activate
            make lint
    


